# TODO: move this to a config file or DB...

WEBSITE_BLOCK_LABEL = 'website'
DOCUMENT_BLOCK_LABEL = 'document'
EMAIL_THREAD_BLOCK_LABEL = 'email_thread'
MESSAGE_THREAD_BLOCK_LABEL = 'message_thread'
COMMENT_BLOCK_LABEL = 'comment'
ACCOUNT_BLOCK_LABEL = 'account'
ACTIVITY_BLOCK_LABEL = 'activity'
CALL_BLOCK_LABEL = 'call'
CONTACT_BLOCK_LABEL = 'contact'
DEAL_BLOCK_LABEL = 'deal'
EVENT_BLOCK_LABEL = 'event'
LEAD_BLOCK_LABEL = 'lead'
TASK_BLOCK_LABEL = 'task'
TICKET_BLOCK_LABEL = 'ticket'
USER_BLOCK_LABEL = 'user'
ORGANIZATION_BLOCK_LABEL = 'organization'
GROUP_BLOCK_LABEL = 'group'
METRIC_BLOCK_LABEL = 'metric'
BRAND_BLOCK_LABEL = 'brand'
MESSAGE_BLOCK_LABEL = 'message'
CHANNEL_BLOCK_LABEL = 'channel'

SUPPORTED_BLOCK_LABELS = set([
    WEBSITE_BLOCK_LABEL,
    DOCUMENT_BLOCK_LABEL,
    EMAIL_THREAD_BLOCK_LABEL,
    MESSAGE_THREAD_BLOCK_LABEL,
    COMMENT_BLOCK_LABEL,
    ACCOUNT_BLOCK_LABEL,
    ACTIVITY_BLOCK_LABEL,
    CALL_BLOCK_LABEL,
    CONTACT_BLOCK_LABEL,
    DEAL_BLOCK_LABEL,
    EVENT_BLOCK_LABEL,
    LEAD_BLOCK_LABEL,
    TASK_BLOCK_LABEL,
    TICKET_BLOCK_LABEL,
    USER_BLOCK_LABEL,
    ORGANIZATION_BLOCK_LABEL,
    GROUP_BLOCK_LABEL,
    METRIC_BLOCK_LABEL,
    BRAND_BLOCK_LABEL,
    MESSAGE_BLOCK_LABEL,
    CHANNEL_BLOCK_LABEL,
])
