# TODO: move this to a config file or DB...

WEBSITE_BLOCK_LABEL = 'website'
DOCUMENT_BLOCK_LABEL = 'document'
EMAIL_THREAD_BLOCK_LABEL = 'email_thread'
MESSAGE_THREAD_BLOCK_LABEL = 'message_thread'
NOTE_BLOCK_LABEL = 'note'
ACCOUNT_BLOCK_LABEL = 'account'
ACTIVITY_BLOCK_LABEL = 'activity'
CALL_BLOCK_LABEL = 'call'
CONTACT_BLOCK_LABEL = 'contact'
DEAL_BLOCK_LABEL = 'deal'
EVENT_BLOCK_LABEL = 'event'
LEAD_BLOCK_LABEL = 'lead'
TASK_BLOCK_LABEL = 'task'

SUPPORTED_BLOCK_LABELS = set([
    WEBSITE_BLOCK_LABEL,
    DOCUMENT_BLOCK_LABEL,
    EMAIL_THREAD_BLOCK_LABEL,
    MESSAGE_THREAD_BLOCK_LABEL,
    NOTE_BLOCK_LABEL,
    ACCOUNT_BLOCK_LABEL,
    ACTIVITY_BLOCK_LABEL,
    CALL_BLOCK_LABEL,
    CONTACT_BLOCK_LABEL,
    DEAL_BLOCK_LABEL,
    EVENT_BLOCK_LABEL,
    LEAD_BLOCK_LABEL,
    TASK_BLOCK_LABEL
])
