/** @type {import('tailwindcss').Config} */
const colors = require("tailwindcss/colors");

module.exports = {
  content: ["./app/**/*.{js,ts,jsx,tsx}", "./components/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      borderRadius: {
        theme: "4px",
      },
      colors: {
        brand: {
          1: "hsl(var(--brand-1) / <alpha-value>)",
          2: "hsl(var(--brand-2) / <alpha-value>)",
          3: "hsl(var(--brand-3) / <alpha-value>)",
          4: "hsl(var(--brand-4) / <alpha-value>)",
          5: "hsl(var(--brand-5) / <alpha-value>)",
          6: "hsl(var(--brand-6) / <alpha-value>)",
          7: "hsl(var(--brand-7) / <alpha-value>)",
          8: "hsl(var(--brand-8) / <alpha-value>)",
          9: "hsl(var(--brand-9) / <alpha-value>)",
          10: "hsl(var(--brand-10) / <alpha-value>)",
          11: "hsl(var(--brand-11) / <alpha-value>)",
          12: "hsl(var(--brand-12) / <alpha-value>)",
          base: "hsl(var(--brand-1) / <alpha-value>)",
          "bg-subtle": "hsl(var(--brand-2) / <alpha-value>)",
          bg: "hsl(var(--brand-3) / <alpha-value>)",
          "bg-hover": "hsl(var(--brand-4) / <alpha-value>)",
          "bg-active": "hsl(var(--brand-5) / <alpha-value>)",
          line: "hsl(var(--brand-6) / <alpha-value>)",
          border: "hsl(var(--brand-7) / <alpha-value>)",
          "border-hover": "hsl(var(--brand-8) / <alpha-value>)",
          solid: "hsl(var(--brand-9) / <alpha-value>)",
          "solid-hover": "hsl(var(--brand-10) / <alpha-value>)",
          text: "hsl(var(--brand-11) / <alpha-value>)",
          "text-contrast": "hsl(var(--brand-12) / <alpha-value>)",
          "on-solid": colors.white,
        },
        accent: {
          1: "hsl(var(--accent-1) / <alpha-value>)",
          2: "hsl(var(--accent-2) / <alpha-value>)",
          3: "hsl(var(--accent-3) / <alpha-value>)",
          4: "hsl(var(--accent-4) / <alpha-value>)",
          5: "hsl(var(--accent-5) / <alpha-value>)",
          6: "hsl(var(--accent-6) / <alpha-value>)",
          7: "hsl(var(--accent-7) / <alpha-value>)",
          8: "hsl(var(--accent-8) / <alpha-value>)",
          9: "hsl(var(--accent-9) / <alpha-value>)",
          10: "hsl(var(--accent-10) / <alpha-value>)",
          11: "hsl(var(--accent-11) / <alpha-value>)",
          12: "hsl(var(--accent-12) / <alpha-value>)",
          base: "hsl(var(--accent-1) / <alpha-value>)",
          "bg-subtle": "hsl(var(--accent-2) / <alpha-value>)",
          bg: "hsl(var(--accent-3) / <alpha-value>)",
          "bg-hover": "hsl(var(--accent-4) / <alpha-value>)",
          "bg-active": "hsl(var(--accent-5) / <alpha-value>)",
          line: "hsl(var(--accent-6) / <alpha-value>)",
          border: "hsl(var(--accent-7) / <alpha-value>)",
          "border-hover": "hsl(var(--accent-8) / <alpha-value>)",
          solid: "hsl(var(--accent-9) / <alpha-value>)",
          "solid-hover": "hsl(var(--accent-10) / <alpha-value>)",
          text: "hsl(var(--accent-11) / <alpha-value>)",
          "text-contrast": "hsl(var(--accent-12) / <alpha-value>)",
          "on-solid": colors.white,
        },
        neutral: {
          1: "hsl(var(--neutral-1) / <alpha-value>)",
          2: "hsl(var(--neutral-2) / <alpha-value>)",
          3: "hsl(var(--neutral-3) / <alpha-value>)",
          4: "hsl(var(--neutral-4) / <alpha-value>)",
          5: "hsl(var(--neutral-5) / <alpha-value>)",
          6: "hsl(var(--neutral-6) / <alpha-value>)",
          7: "hsl(var(--neutral-7) / <alpha-value>)",
          8: "hsl(var(--neutral-8) / <alpha-value>)",
          9: "hsl(var(--neutral-9) / <alpha-value>)",
          10: "hsl(var(--neutral-10) / <alpha-value>)",
          11: "hsl(var(--neutral-11) / <alpha-value>)",
          12: "hsl(var(--neutral-12) / <alpha-value>)",
          base: "hsl(var(--neutral-1) / <alpha-value>)",
          "bg-subtle": "hsl(var(--neutral-2) / <alpha-value>)",
          bg: "hsl(var(--neutral-3) / <alpha-value>)",
          "bg-hover": "hsl(var(--neutral-4) / <alpha-value>)",
          "bg-active": "hsl(var(--neutral-5) / <alpha-value>)",
          line: "hsl(var(--neutral-6) / <alpha-value>)",
          border: "hsl(var(--neutral-7) / <alpha-value>)",
          "border-hover": "hsl(var(--neutral-8) / <alpha-value>)",
          solid: "hsl(var(--neutral-9) / <alpha-value>)",
          "solid-hover": "hsl(var(--neutral-10) / <alpha-value>)",
          text: "hsl(var(--neutral-11) / <alpha-value>)",
          "text-contrast": "hsl(var(--neutral-12) / <alpha-value>)",
          "on-solid": colors.white,
        },
        gray: {
          1: "hsl(var(--gray-1) / <alpha-value>)",
          2: "hsl(var(--gray-2) / <alpha-value>)",
          3: "hsl(var(--gray-3) / <alpha-value>)",
          4: "hsl(var(--gray-4) / <alpha-value>)",
          5: "hsl(var(--gray-5) / <alpha-value>)",
          6: "hsl(var(--gray-6) / <alpha-value>)",
          7: "hsl(var(--gray-7) / <alpha-value>)",
          8: "hsl(var(--gray-8) / <alpha-value>)",
          9: "hsl(var(--gray-9) / <alpha-value>)",
          10: "hsl(var(--gray-10) / <alpha-value>)",
          11: "hsl(var(--gray-11) / <alpha-value>)",
          12: "hsl(var(--gray-12) / <alpha-value>)",
          base: "hsl(var(--gray-1) / <alpha-value>)",
          "bg-subtle": "hsl(var(--gray-2) / <alpha-value>)",
          bg: "hsl(var(--gray-3) / <alpha-value>)",
          "bg-hover": "hsl(var(--gray-4) / <alpha-value>)",
          "bg-active": "hsl(var(--gray-5) / <alpha-value>)",
          line: "hsl(var(--gray-6) / <alpha-value>)",
          border: "hsl(var(--gray-7) / <alpha-value>)",
          "border-hover": "hsl(var(--gray-8) / <alpha-value>)",
          solid: "hsl(var(--gray-9) / <alpha-value>)",
          "solid-hover": "hsl(var(--gray-10) / <alpha-value>)",
          text: "hsl(var(--gray-11) / <alpha-value>)",
          "text-contrast": "hsl(var(--gray-12) / <alpha-value>)",
          "on-solid": colors.white,
        },
        success: {
          1: "hsl(var(--success-1) / <alpha-value>)",
          2: "hsl(var(--success-2) / <alpha-value>)",
          3: "hsl(var(--success-3) / <alpha-value>)",
          4: "hsl(var(--success-4) / <alpha-value>)",
          5: "hsl(var(--success-5) / <alpha-value>)",
          6: "hsl(var(--success-6) / <alpha-value>)",
          7: "hsl(var(--success-7) / <alpha-value>)",
          8: "hsl(var(--success-8) / <alpha-value>)",
          9: "hsl(var(--success-9) / <alpha-value>)",
          10: "hsl(var(--success-10) / <alpha-value>)",
          11: "hsl(var(--success-11) / <alpha-value>)",
          12: "hsl(var(--success-12) / <alpha-value>)",
          base: "hsl(var(--success-1) / <alpha-value>)",
          "bg-subtle": "hsl(var(--success-2) / <alpha-value>)",
          bg: "hsl(var(--success-3) / <alpha-value>)",
          "bg-hover": "hsl(var(--success-4) / <alpha-value>)",
          "bg-active": "hsl(var(--success-5) / <alpha-value>)",
          line: "hsl(var(--success-6) / <alpha-value>)",
          border: "hsl(var(--success-7) / <alpha-value>)",
          "border-hover": "hsl(var(--success-8) / <alpha-value>)",
          solid: "hsl(var(--success-9) / <alpha-value>)",
          "solid-hover": "hsl(var(--success-10) / <alpha-value>)",
          text: "hsl(var(--success-11) / <alpha-value>)",
          "text-contrast": "hsl(var(--success-12) / <alpha-value>)",
          "on-solid": colors.white,
        },
        info: {
          1: "hsl(var(--info-1) / <alpha-value>)",
          2: "hsl(var(--info-2) / <alpha-value>)",
          3: "hsl(var(--info-3) / <alpha-value>)",
          4: "hsl(var(--info-4) / <alpha-value>)",
          5: "hsl(var(--info-5) / <alpha-value>)",
          6: "hsl(var(--info-6) / <alpha-value>)",
          7: "hsl(var(--info-7) / <alpha-value>)",
          8: "hsl(var(--info-8) / <alpha-value>)",
          9: "hsl(var(--info-9) / <alpha-value>)",
          10: "hsl(var(--info-10) / <alpha-value>)",
          11: "hsl(var(--info-11) / <alpha-value>)",
          12: "hsl(var(--info-12) / <alpha-value>)",
          base: "hsl(var(--info-1) / <alpha-value>)",
          "bg-subtle": "hsl(var(--info-2) / <alpha-value>)",
          bg: "hsl(var(--info-3) / <alpha-value>)",
          "bg-hover": "hsl(var(--info-4) / <alpha-value>)",
          "bg-active": "hsl(var(--info-5) / <alpha-value>)",
          line: "hsl(var(--info-6) / <alpha-value>)",
          border: "hsl(var(--info-7) / <alpha-value>)",
          "border-hover": "hsl(var(--info-8) / <alpha-value>)",
          solid: "hsl(var(--info-9) / <alpha-value>)",
          "solid-hover": "hsl(var(--info-10) / <alpha-value>)",
          text: "hsl(var(--info-11) / <alpha-value>)",
          "text-contrast": "hsl(var(--info-12) / <alpha-value>)",
          "on-solid": colors.black,
        },
        warning: {
          1: "hsl(var(--warning-1) / <alpha-value>)",
          2: "hsl(var(--warning-2) / <alpha-value>)",
          3: "hsl(var(--warning-3) / <alpha-value>)",
          4: "hsl(var(--warning-4) / <alpha-value>)",
          5: "hsl(var(--warning-5) / <alpha-value>)",
          6: "hsl(var(--warning-6) / <alpha-value>)",
          7: "hsl(var(--warning-7) / <alpha-value>)",
          8: "hsl(var(--warning-8) / <alpha-value>)",
          9: "hsl(var(--warning-9) / <alpha-value>)",
          10: "hsl(var(--warning-10) / <alpha-value>)",
          11: "hsl(var(--warning-11) / <alpha-value>)",
          12: "hsl(var(--warning-12) / <alpha-value>)",
          base: "hsl(var(--warning-1) / <alpha-value>)",
          "bg-subtle": "hsl(var(--warning-2) / <alpha-value>)",
          bg: "hsl(var(--warning-3) / <alpha-value>)",
          "bg-hover": "hsl(var(--warning-4) / <alpha-value>)",
          "bg-active": "hsl(var(--warning-5) / <alpha-value>)",
          line: "hsl(var(--warning-6) / <alpha-value>)",
          border: "hsl(var(--warning-7) / <alpha-value>)",
          "border-hover": "hsl(var(--warning-8) / <alpha-value>)",
          solid: "hsl(var(--warning-9) / <alpha-value>)",
          "solid-hover": "hsl(var(--warning-10) / <alpha-value>)",
          text: "hsl(var(--warning-11) / <alpha-value>)",
          "text-contrast": "hsl(var(--warning-12) / <alpha-value>)",
          "on-solid": colors.white,
        },
        danger: {
          1: "hsl(var(--danger-1) / <alpha-value>)",
          2: "hsl(var(--danger-2) / <alpha-value>)",
          3: "hsl(var(--danger-3) / <alpha-value>)",
          4: "hsl(var(--danger-4) / <alpha-value>)",
          5: "hsl(var(--danger-5) / <alpha-value>)",
          6: "hsl(var(--danger-6) / <alpha-value>)",
          7: "hsl(var(--danger-7) / <alpha-value>)",
          8: "hsl(var(--danger-8) / <alpha-value>)",
          9: "hsl(var(--danger-9) / <alpha-value>)",
          10: "hsl(var(--danger-10) / <alpha-value>)",
          11: "hsl(var(--danger-11) / <alpha-value>)",
          12: "hsl(var(--danger-12) / <alpha-value>)",
          base: "hsl(var(--danger-1) / <alpha-value>)",
          "bg-subtle": "hsl(var(--danger-2) / <alpha-value>)",
          bg: "hsl(var(--danger-3) / <alpha-value>)",
          "bg-hover": "hsl(var(--danger-4) / <alpha-value>)",
          "bg-active": "hsl(var(--danger-5) / <alpha-value>)",
          line: "hsl(var(--danger-6) / <alpha-value>)",
          border: "hsl(var(--danger-7) / <alpha-value>)",
          "border-hover": "hsl(var(--danger-8) / <alpha-value>)",
          solid: "hsl(var(--danger-9) / <alpha-value>)",
          "solid-hover": "hsl(var(--danger-10) / <alpha-value>)",
          text: "hsl(var(--danger-11) / <alpha-value>)",
          "text-contrast": "hsl(var(--danger-12) / <alpha-value>)",
          "on-solid": colors.white,
        },
      },
      spacing: {
        128: "32rem",
        "theme-1/8": "0.1875rem",
        "theme-1/4": "0.375rem",
        "theme-1/2": "0.75rem",
        theme: "1.5rem",
        "theme-3/2": "2.25rem",
        "theme-2": "3rem",
      },
    },
  },
  plugins: [],
};
