/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./app/**/*.{ts,tsx}",
  ],
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        brand: {
          1: "hsl(var(--brand-1) / <alpha-value>)",
          2: "hsl(var(--brand-2) / <alpha-value>)",
          3: "hsl(var(--brand-3) / <alpha-value>)",
          4: "hsl(var(--brand-4) / <alpha-value>)",
          5: "hsl(var(--brand-5) / <alpha-value>)",
          6: "hsl(var(--brand-6) / <alpha-value>)",
          7: "hsl(var(--brand-7) / <alpha-value>)",
          8: "hsl(var(--brand-8) / <alpha-value>)",
          9: "hsl(var(--brand-9) / <alpha-value>)",
          10: "hsl(var(--brand-10) / <alpha-value>)",
          11: "hsl(var(--brand-11) / <alpha-value>)",
          12: "hsl(var(--brand-12) / <alpha-value>)",
        },
        neutral: {
          0: "hsl(var(--neutral-0) / <alpha-value>)",
          1: "hsl(var(--neutral-1) / <alpha-value>)",
          2: "hsl(var(--neutral-2) / <alpha-value>)",
          3: "hsl(var(--neutral-3) / <alpha-value>)",
          4: "hsl(var(--neutral-4) / <alpha-value>)",
          5: "hsl(var(--neutral-5) / <alpha-value>)",
          6: "hsl(var(--neutral-6) / <alpha-value>)",
          7: "hsl(var(--neutral-7) / <alpha-value>)",
          8: "hsl(var(--neutral-8) / <alpha-value>)",
          9: "hsl(var(--neutral-9) / <alpha-value>)",
          10: "hsl(var(--neutral-10) / <alpha-value>)",
          11: "hsl(var(--neutral-11) / <alpha-value>)",
          12: "hsl(var(--neutral-12) / <alpha-value>)",
          13: "hsl(var(--neutral-13) / <alpha-value>)",
        },
        gray: {
          0: "hsl(var(--gray-0) / <alpha-value>)",
          1: "hsl(var(--gray-1) / <alpha-value>)",
          2: "hsl(var(--gray-2) / <alpha-value>)",
          3: "hsl(var(--gray-3) / <alpha-value>)",
          4: "hsl(var(--gray-4) / <alpha-value>)",
          5: "hsl(var(--gray-5) / <alpha-value>)",
          6: "hsl(var(--gray-6) / <alpha-value>)",
          7: "hsl(var(--gray-7) / <alpha-value>)",
          8: "hsl(var(--gray-8) / <alpha-value>)",
          9: "hsl(var(--gray-9) / <alpha-value>)",
          10: "hsl(var(--gray-10) / <alpha-value>)",
          11: "hsl(var(--gray-11) / <alpha-value>)",
          12: "hsl(var(--gray-12) / <alpha-value>)",
          13: "hsl(var(--gray-13) / <alpha-value>)",
        },
        success: {
          1: "hsl(var(--success-1) / <alpha-value>)",
          2: "hsl(var(--success-2) / <alpha-value>)",
          3: "hsl(var(--success-3) / <alpha-value>)",
          4: "hsl(var(--success-4) / <alpha-value>)",
          5: "hsl(var(--success-5) / <alpha-value>)",
          6: "hsl(var(--success-6) / <alpha-value>)",
          7: "hsl(var(--success-7) / <alpha-value>)",
          8: "hsl(var(--success-8) / <alpha-value>)",
          9: "hsl(var(--success-9) / <alpha-value>)",
          10: "hsl(var(--success-10) / <alpha-value>)",
          11: "hsl(var(--success-11) / <alpha-value>)",
          12: "hsl(var(--success-12) / <alpha-value>)",
        },
        info: {
          1: "hsl(var(--info-1) / <alpha-value>)",
          2: "hsl(var(--info-2) / <alpha-value>)",
          3: "hsl(var(--info-3) / <alpha-value>)",
          4: "hsl(var(--info-4) / <alpha-value>)",
          5: "hsl(var(--info-5) / <alpha-value>)",
          6: "hsl(var(--info-6) / <alpha-value>)",
          7: "hsl(var(--info-7) / <alpha-value>)",
          8: "hsl(var(--info-8) / <alpha-value>)",
          9: "hsl(var(--info-9) / <alpha-value>)",
          10: "hsl(var(--info-10) / <alpha-value>)",
          11: "hsl(var(--info-11) / <alpha-value>)",
          12: "hsl(var(--info-12) / <alpha-value>)",
        },
        warning: {
          1: "hsl(var(--warning-1) / <alpha-value>)",
          2: "hsl(var(--warning-2) / <alpha-value>)",
          3: "hsl(var(--warning-3) / <alpha-value>)",
          4: "hsl(var(--warning-4) / <alpha-value>)",
          5: "hsl(var(--warning-5) / <alpha-value>)",
          6: "hsl(var(--warning-6) / <alpha-value>)",
          7: "hsl(var(--warning-7) / <alpha-value>)",
          8: "hsl(var(--warning-8) / <alpha-value>)",
          9: "hsl(var(--warning-9) / <alpha-value>)",
          10: "hsl(var(--warning-10) / <alpha-value>)",
          11: "hsl(var(--warning-11) / <alpha-value>)",
          12: "hsl(var(--warning-12) / <alpha-value>)",
        },
        danger: {
          1: "hsl(var(--danger-1) / <alpha-value>)",
          2: "hsl(var(--danger-2) / <alpha-value>)",
          3: "hsl(var(--danger-3) / <alpha-value>)",
          4: "hsl(var(--danger-4) / <alpha-value>)",
          5: "hsl(var(--danger-5) / <alpha-value>)",
          6: "hsl(var(--danger-6) / <alpha-value>)",
          7: "hsl(var(--danger-7) / <alpha-value>)",
          8: "hsl(var(--danger-8) / <alpha-value>)",
          9: "hsl(var(--danger-9) / <alpha-value>)",
          10: "hsl(var(--danger-10) / <alpha-value>)",
          11: "hsl(var(--danger-11) / <alpha-value>)",
          12: "hsl(var(--danger-12) / <alpha-value>)",
        },
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
          1: "hsl(var(--accent-1) / <alpha-value>)",
          2: "hsl(var(--accent-2) / <alpha-value>)",
          3: "hsl(var(--accent-3) / <alpha-value>)",
          4: "hsl(var(--accent-4) / <alpha-value>)",
          5: "hsl(var(--accent-5) / <alpha-value>)",
          6: "hsl(var(--accent-6) / <alpha-value>)",
          7: "hsl(var(--accent-7) / <alpha-value>)",
          8: "hsl(var(--accent-8) / <alpha-value>)",
          9: "hsl(var(--accent-9) / <alpha-value>)",
          10: "hsl(var(--accent-10) / <alpha-value>)",
          11: "hsl(var(--accent-11) / <alpha-value>)",
          12: "hsl(var(--accent-12) / <alpha-value>)",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      fontFamily: {
        sans: ["var(--font-sans)"],
        mono: ["var(--font-mono)"],
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: 0 },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: 0 },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
