name: fixie-deploy
on: [push, workflow_dispatch]
jobs:
  aws_cdk:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install requirements
        run: python -m pip install -r requirements.txt
        working-directory: ./fixie-agent
      - name: Deploy to Fixie
        run: python -m fixie agent deploy --validate
        working-directory: ./fixie-agent
