name: fixie-deploy
on: [push, workflow_dispatch]
jobs:
  aws_cdk:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true
      - name: Install requirements
        run: poetry install --no-interaction --no-root
        working-directory: ./fixie-agent

      - name: Deploy to Fixie
        run: poetry run fixie agent deploy --validate
        working-directory: ./fixie-agent
